<a href="https://colab.research.google.com/github/mediqslot/hamoye1/blob/main/test_tagalong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv

--2023-10-02 11:59:44--  https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-repository-file-5c1aeb/441122776/7768140?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231002%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231002T115944Z&X-Amz-Expires=300&X-Amz-Signature=f29d97df2d61e896e42b55a1502e795fe5803ef1706799c18907f31999f3832f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=441122776&response-content-disposition=attachment%3Bfilename%3DFoodBalanceSheets_E_Africa_NOFLAG.csv&response-content-type=application%2Fvnd.ms-excel [following]
--2023-10-02 11:59:44--  https://objects.githubusercontent.com/github-production-repository-file-5c1aeb/441122776/7768140?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231002%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231002T115944Z&X-Amz-Expires=300&X-Amz-Signature=f29d97df2d61e896e42b55a1502e795fe5803ef1706799c18907f31999f3832f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=441122776&response-content-disposition=attachment%3Bfilename%3DFoodBalanceSheets_E_Africa_NOFLAG.csv&response-content-type=application%2Fvnd.ms-excel
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8603007 (8.2M) [application/vnd.ms-excel]
Saving to: ‘FoodBalanceSheets_E_Africa_NOFLAG.csv’

FoodBalanceSheets_E 100%[===================>]   8.20M  --.-KB/s    in 0.08s

2023-10-02 11:59:45 (102 MB/s) - ‘FoodBalanceSheets_E_Africa_NOFLAG.csv’ saved [8603007/8603007]

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/FoodBalanceSheets_E_Africa_NOFLAG.csv',encoding="latin-1")

In [ ]:
data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [ ]:
data.shape

(60943, 12)

In [ ]:
uniq= data["Area"].nunique()
print(f'Total unique countries: {uniq}')

Total unique countries: 49

In [ ]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: ignored

In [ ]:
data.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [ ]:
data.groupby("Item").sum()

<ipython-input-37-864f06e73408>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby("Item").sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [ ]:
data.groupby('Element').sum()

<ipython-input-38-9de777f02d07>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [ ]:
data.mean()

<ipython-input-20-abc01cf6c622>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.mean()

Area Code        134.265576
Item Code       2687.176706
Element Code    3814.856456
Y2014            134.196282
Y2015            135.235966
Y2016            136.555222
Y2017            140.917765
Y2018            143.758381
dtype: float64

In [ ]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [ ]:
data.loc['Madagascar']

KeyError: ignored

In [ ]:
import numpy as np

arr  = np.array([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])
print('a', arr[:1, 1:])
print('c', arr[:2, 1:])
print('d', arr[:2, 0:])
print('e', arr[:1, :])

a [[89 63]]
c [[89 63]
 [92 48]]
d [[94 89 63]
 [93 92 48]]
e [[94 89 63]]